//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyTrainer.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}
